### ISSUE TITLE
Redesign freelancers page

### ISSUE THREAD

**Issue by gonzaloserrano** [bcneng/website#105]
- [ ] dark background does not look well with dark navbar
- [ ] desktop version uses a table 🤮 
- [x] not responsive -- fixed at https://github.com/bcneng/website/pull/106

**Comment by cmmata** [comment]
As it's a "data table" with up to 7 columns, how should the mobile version look like? Do you have an idea?

I could help with this, but the only alternative that comes to my mind is breaking the table into one "box" per person, putting all the information in vertical. Something like
```
Name & Handler: XXX
Services: XXX
Skills: XXX
Availability: XXX
Pricing Model: XXX
Web: XXX
LinkedIn: XXX
```

**Comment by gonzaloserrano** [comment]
Agree with your suggestion. If you want to design the desktop version too, feel free.

**Comment by gonzaloserrano** [comment]
Sure! We can iterate on the desktop version later.
