### ISSUE TITLE
Create page/section for sponsors or supporters

### ISSUE THREAD

**Issue by smoya** [bcneng/website#113]
Digital ocean is supporting us by giving a budget for hosting our apps. However, we do not have any section on the website to mention that, which is IMHO the minimum expression of being thankful to them.
Slack is also offering the Standard plan at no cost, so worth to include them as well :)

This feature request is to add a new section on the main page or rather a new page for listing sponsors/partners/supporters and to include our two current ones.

**Comment by chandu-jadhav** [comment]
hey can I  work on this issue?

**Comment by smoya** [comment]
For some reason, we missed this one @chandu-jadhav. Feel free to work on this one. Happy to provide you all details you need.

**Comment by MANOJ-BHAMARADDI** [comment]
@smoya is this still open?

**Comment by smoya** [comment]
> @smoya is this still open?

Oh, no. This is already done and visible at https://bcneng.org

**Comment by MANOJ-BHAMARADDI** [comment]
ok , no problem
