### ISSUE TITLE
Improve about

### ISSUE THREAD

**Issue by sdecandelario** [bcneng/website#26]
Adapt the `about` section and change the link of the invited to https://slack.bcneng.net/

Ideas to the content of the about page are welcome!

**Comment by alombarte** [comment]
IMO the page should at least answer the following questions (WHAT, WHY, WHO, HOW) that come now to my mind:

WHAT and WHY
- Why does it exist? 
- What is this community and who is it's target audience?
- What is the legal form of this "community"
- What are the ongoing efforts

WHO
- Governance
- Collaborators
- Companies

HOW
- How to get involved
- Membership?

**Comment by sdecandelario** [comment]
The about section is adapted, if all give it the check for me this issue is closed. Any comments?

**Comment by gonzaloserrano** [comment]
Fixed partially in https://github.com/bcneng/bcneng.github.io/pull/32, but you make very good points that are not in the about page.

**Comment by sdecandelario** [comment]
We can close this issue? Or we need to do some improvements?

**Comment by gonzaloserrano** [comment]
I'm reopening since I think we can do it better

**Comment by ignasi35** [comment]
> I'm reopening since I think we can do it better

@gonzaloserrano what do you think is lacking?

PS: May I suggest you opened a separate, more specific issue? :-)
