### ISSUE TITLE
Remove archived provjects from pinned repos list

### ISSUE THREAD

**Issue by ignasi35** [bcneng/website#87]
(creating this here because there's no meta issue tracker for the Bcn Eng organization)

The list of popular repos on the summary of the organization lists archived projects. That's a bit confusing. Please remove the archived projects from the list.

<img width="1007" alt="Screenshot 2021-09-04 at 15 22 50" src="https://user-images.githubusercontent.com/762126/132095973-2403c86a-8531-47f3-8242-3e4827808548.png">

**Comment by gonzaloserrano** [comment]
Hmmm they are not pinned, so I'm not sure we can do that unless removed?
